// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nanuhhfdldyiefdthlrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hbnVoaGZkbGR5aWVmZHRobHJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNDU2MTMsImV4cCI6MjA3MTYyMTYxM30.AOXpFdG5K9bjOZwwWxiZ6GpJrRHx-bLCVfWTbBJdAls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});